version: "3"
services:
    lim:
        image: "fortifydocker/lim:21.2"
        container_name: lim
        ports:
            - "8090:8090"
        environment:
          - LimUseSSL=false
          - LimAdminWebSiteName=LimAdmin
          - LimServiceSiteName=LimService
          - LimApiSiteName=LimAPI
          - LimDirectory=c:\lim
          - certpath=c:\lim\limcert.pfx
          - certpassword=limcert
          - LimAdminUsername=limuser
          - LimAdminPassword=limuser!1
          - LimAdminEmail=limadmin@limadmin.com
          - LimAdminFriendlyName=LimAdmin!
        restart: always
        volumes:
          - lim:c:/lim
        deploy:
            resources:
                limits:
                    cpus: '2'
                    memory: 8g

volumes:
  lim: